language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token: 152462145e4486e4f013fbf82a6a95812808bbe4223bc84c0bee9738aeab0f70

# Branches to be built or not
branches:
  # Blacklist these branches
  except:
    - gh-pages

# Before Installing Software/Dependencies Needed
before_install:
  - sh -c "cp ./config/config.sample.php ./config/config.php"

# Install Software/Dependencies Needed
install:
  - git submodule update --init --recursive
  - composer install --dev --no-interaction

before_script:
  - phpenv rehash

script:
  - ./bin/run-tests
  - ./bin/run-codesniffer y

after_success:
  - vendor/bin/test-reporter

notifications:
  email: false
