language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

# Branches to be built or not
branches:
  # Blacklist these branches
  except:
    - gh-pages

# Before Installing Software/Dependencies Needed
before_install:
  - composer self-update
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
  - sh -c "cp ./config/config.sample.php ./config/config.php"

# Install Software/Dependencies Needed
install:
  - git submodule update --init --recursive
  - composer install --dev --no-interaction

before_script:
  - phpenv rehash

script:
  - ./bin/run-tests
  - ./bin/run-codesniffer y

notifications:
  email: false
